# Generated by Django 6.0.8 on 2026-09-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('offered', models.JSONField()),
                ('prereqs', models.JSONField()),
                ('coreqs', models.JSONField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8)),
                ('position', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['kind', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('track', models.CharField(max_length=32)),
                ('completed', models.JSONField()),
                ('start_year', models.IntegerField()),
                ('start_season', models.CharField(max_length=16)),
                ('num_terms', models.IntegerField()),
                ('max_credits_per_term', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('rule', models.CharField(max_length=16)),
                ('n', models.IntegerField()),
                ('courses', models.JSONField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='planapi.program')),
            ],
            options={
                'ordering': ['program', 'position'],
            },
        ),
    ]
