# Generated by Django 6.0.8 on 2026-09-27 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=32)),
                ('input', models.JSONField()),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('active_key', models.CharField(max_length=64, null=True, unique=True)),
                ('status', models.CharField(max_length=8)),
                ('params', models.TextField()),
                ('plan', models.TextField(null=True)),
                ('engine', models.TextField(null=True)),
                ('error', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
