# Generated by Django 6.0.8 on 2026-09-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planapi', '0002_planjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='planjob',
            name='export_error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planjob',
            name='export_key',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='planjob',
            name='export_status',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='planjob',
            name='exported_at',
            field=models.DateTimeField(null=True),
        ),
    ]
